arangodb:
  image: arangodb/arangodb:2.8.9
  ports:
    - "8529:8529"
  environment:
    - ARANGO_NO_AUTH=true
web:
  image: polluxx/poc-marketing-automation
  #build: .
  ports:
    - "5001:5001"
  links:
    - arangodb
  environment:
    - ARANGO_NO_AUTH=true
    - "SERVICE_URL=http://localhost:5000"
    - "SERVICE_API_URL=http://localhost:5000/api"
